config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :discription, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Basecamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
    <div class="d-flex justify-content-center" style="margin-top:100px">
          <div>
             <%=image_tag"img.jpg"%>
             <h1>COLLABORATE</h1>
        </div>
    </div>
    <div class="d-flex justify-content-center">


<% if current_user %>
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-warning"><%= link_to 'Projects', projects_path , class:"nav-link active "%></button>
  <button type="button" class="btn btn-warning">   <%= link_to "Edit Account", edit_user_registration_path, class:"nav-link active" %></button>
  <button type="button" class="btn btn-warning"> <%= link_to('Logout', destroy_user_session_path, 'data-turbo-method': :delete , class:"nav-link active") %></button>
</div>
            
         
           



<% else %>

        <div class="log_sign">
            <%= link_to 'Sign in', new_user_session_path, class: "btn btn-primary" %>
            <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary" %>

        </div>
    </div>

<% end %>

<style>
.log_sign{
    margin:100px;
}
.btn-group{
    margin-top:100px;
}
h1{
    font-size:50px;
    font-weight:900;
    margin-top:20px
}
</style>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div>
    <%= form.label :discription, style: "display: block" %>
    <%= form.text_area :discription, class: "form-control" %>
  </div>

    <div>
        <%= form.number_field :user_id, id: :project_user_id, value: current_user.id, type: :hidden%>
      </div>

  <div>
  <p style="margin-top:20px">
    <%= form.submit class: "btn btn-primary" %>
  </div>
  </p>
<% end %>

<style>
  .form-control{
    width:400px;
  }
</style>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Discription:</strong>
    <%= project.discription %>
  </p>


</div>

app/views/projects/edit.html.erb
    <div class="d-flex justify-content-center" style="margin-top:100px">
          <div>
             <h1>Editing project</h1>

             <%= render "form", project: @project %>

        <br>

        <div>
          <%= link_to "Show this project", @project, class: "btn btn-primary" %> 
          <%= link_to "Back ", projects_path, class: "btn btn-primary" %>
        </div>
        </div>
    </div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>
 <div class="d-flex justify-content-center" style="margin-top:100px">
          <div>
            <h1>Project</h1>
                <p style=" margin-left:20px;">
       <%= link_to "New project", new_project_path, class: "btn btn-primary" %><br>
    </p>
        </div>
    </div>




 <h5 style="margin-left:100px">All project</h5>

<div class="card text-white bg-secondary mb-3" style="max-width: 25rem; margin-left:100px;">
   
  <div id="projects" class="">
  <% @projects.each do |project| %>
    <% if project.user_id == current_user.id %>
  
    <%= render project %>
    <p style=" margin-left:20px;">
      <%= link_to "Show this project", project, class: "btn btn-primary" %>
    </p>


    <p style=" margin-left:20px;">
       <%= link_to "Back", root_path, class: "btn btn-primary"%>
    </p>
    <% end %>
  <% end %>
</div>
</div>

app/views/projects/new.html.erb
<div class="container" style="margin-top:100px">
      <div class="d-flex justify-content-center">
         <h1>New projectvbg</h1>
      </div>
       <div class="d-flex justify-content-center">
          <%= render "form", project: @project %>

        <br>

        <div>
      </div>

     
</div>
<div class="container">
      <div class="d-flex justify-content-center">
            <%= link_to "Back", projects_path, class: "btn btn-primary" %>
      </div>
</div>
<div>

app/views/projects/show.html.erb
    <div class="d-flex justify-content-center" style="margin-top:100px">
          <div class="card" style="width:400px;padding-left:20px">
             <p style="color: green"><%= notice %></p>

              <%= render @project %>

              <div>
                <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-primary"%><br> <br>
                <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-primary" %><br> 
                <%= link_to "Back to projects", projects_path, class: "btn btn-primary" %><br>

              
              </div>
        </div>
    </div>